### ISSUE TITLE
Error when patching

### ISSUE THREAD

**Issue by Alonely0** [tobeqz/discord-extensions#1]
If discord is closed when patching all goes ok, but if it is opened I get this error
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, stat '/home/guillem/.config/discord/SingletonCookie'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/guillem/.config/discord/SingletonCookie'
}
```

If it can help, I just installed discord because I had installed canary, and this only works on stable.

**Comment by Alonely0** [comment]
Possible solution: kill discord process before start patching.
This library could help: https://www.npmjs.com/package/fkill

**Comment by jorikvanveen** [comment]
I was planning to make a workaround, but killing the process is probably better, since you have to restart discord anyway. Working on it!

**Comment by tobeqz** [comment]
The actual error is caused by this piece of code

https://github.com/tobeqz/discord-extensions/blob/182a0e9cafecf58fe8e5f05b59d8ab53f5bf34ed/src/get_version_dirs.ts#L27-L42

Which is honestly a horrible way to find installed discord versions.

So I should find a better way to get the version directories and also kill the discord process before starting the patching process.

**Comment by tobeqz** [comment]
![image](https://user-images.githubusercontent.com/83136264/118371793-7c57d500-b5ae-11eb-9a2c-fe8c9553def5.png)
Okay looks like I found a better way to get the currently installed version, instead of looping through all of them
